import type { FieldMetadata, NEMSISSection } from '../types/nemsis';

export const FIELD_REGISTRY: Record<string, FieldMetadata> = {
  // --- ePatient ---
  age: {
    nemsis_element: 'ePatient.15',
    usage: 'mandatory',
    section: 'ePatient',
    description: 'Patient age in years',
    value_type: 'int',
    prompt_template: "What is the patient's age?",
    clinical_label: 'Age',
  },
  sex: {
    nemsis_element: 'ePatient.13',
    usage: 'mandatory',
    section: 'ePatient',
    description: 'Patient gender',
    value_type: 'str',
    allowed_values: ['male', 'female', 'unknown'],
    prompt_template: "What is the patient's sex?",
    clinical_label: 'Sex',
  },

  // --- eScene / eDispatch / eProtocols ---
  incident_location: {
    nemsis_element: 'eScene.15',
    usage: 'recommended',
    section: 'eScene',
    description: 'Location where the incident occurred',
    value_type: 'str',
    prompt_template: 'Where did the incident occur?',
    clinical_label: 'Incident Location',
  },
  initial_acuity: {
    nemsis_element: 'eDispatch.13',
    usage: 'recommended',
    section: 'eDispatch',
    description: 'Initial acuity level assigned at dispatch',
    value_type: 'str',
    allowed_values: ['Critical', 'Emergent', 'Lower Acuity', 'Non-Acute'],
    prompt_template: 'What was the initial acuity level?',
    clinical_label: 'Initial Acuity',
  },
  protocol_used: {
    nemsis_element: 'eProtocols.01',
    usage: 'recommended',
    section: 'eProtocols',
    description: 'EMS protocol followed during the encounter',
    value_type: 'str',
    prompt_template: 'Which protocol was used?',
    clinical_label: 'Protocol Used',
  },

  // --- eSituation ---
  chief_complaint: {
    nemsis_element: 'eSituation.04',
    usage: 'mandatory',
    section: 'eSituation',
    description: 'Primary reason for the EMS encounter',
    value_type: 'str',
    prompt_template: "What is the patient's chief complaint?",
    clinical_label: 'Chief Complaint',
  },
  primary_impression: {
    nemsis_element: 'eSituation.11',
    usage: 'mandatory',
    section: 'eSituation',
    description: "Provider's primary clinical impression",
    value_type: 'str',
    prompt_template: 'What is the primary impression or working diagnosis?',
    clinical_label: 'Primary Impression',
  },
  secondary_impression: {
    nemsis_element: 'eSituation.12',
    usage: 'recommended',
    section: 'eSituation',
    description: "Provider's secondary clinical impression",
    value_type: 'str',
    prompt_template: 'Is there a secondary impression?',
    clinical_label: 'Secondary Impression',
  },
  signs_symptoms: {
    nemsis_element: 'eSituation.09',
    usage: 'recommended',
    section: 'eSituation',
    description: 'Signs and symptoms observed or reported',
    value_type: 'list[str]',
    prompt_template: 'What signs and symptoms were observed?',
    clinical_label: 'Signs & Symptoms',
  },
  events_leading: {
    nemsis_element: 'eSituation.06',
    usage: 'recommended',
    section: 'eSituation',
    description: 'Description of events leading to the incident',
    value_type: 'str',
    prompt_template: 'What events led to this incident?',
    clinical_label: 'Events Leading',
  },

  // --- eHistory ---
  allergies: {
    nemsis_element: 'eHistory.06',
    usage: 'required',
    section: 'eHistory',
    description: 'Known patient allergies',
    value_type: 'list[str]',
    prompt_template: 'Does the patient have any known allergies?',
    clinical_label: 'Allergies',
  },
  medications_current: {
    nemsis_element: 'eHistory.08',
    usage: 'recommended',
    section: 'eHistory',
    description: 'Current medications the patient takes',
    value_type: 'list[str]',
    prompt_template: 'What medications is the patient currently taking?',
    clinical_label: 'Current Medications',
  },
  past_medical_history: {
    nemsis_element: 'eHistory.08',
    usage: 'required',
    section: 'eHistory',
    description: 'Relevant past medical history',
    value_type: 'list[str]',
    prompt_template: "What is the patient's past medical history?",
    clinical_label: 'Past Medical History',
  },

  // --- eVitals ---
  bp_systolic: {
    nemsis_element: 'eVitals.06',
    usage: 'required',
    section: 'eVitals',
    description: 'Systolic blood pressure in mmHg',
    value_type: 'int',
    prompt_template: 'What is the systolic blood pressure?',
    clinical_label: 'Systolic BP',
  },
  bp_diastolic: {
    nemsis_element: 'eVitals.07',
    usage: 'required',
    section: 'eVitals',
    description: 'Diastolic blood pressure in mmHg',
    value_type: 'int',
    prompt_template: 'What is the diastolic blood pressure?',
    clinical_label: 'Diastolic BP',
  },
  heart_rate: {
    nemsis_element: 'eVitals.10',
    usage: 'required',
    section: 'eVitals',
    description: 'Heart rate in beats per minute',
    value_type: 'int',
    prompt_template: 'What is the heart rate?',
    clinical_label: 'Heart Rate',
  },
  respiratory_rate: {
    nemsis_element: 'eVitals.14',
    usage: 'required',
    section: 'eVitals',
    description: 'Respiratory rate in breaths per minute',
    value_type: 'int',
    prompt_template: 'What is the respiratory rate?',
    clinical_label: 'Respiratory Rate',
  },
  spo2: {
    nemsis_element: 'eVitals.12',
    usage: 'required',
    section: 'eVitals',
    description: 'Pulse oximetry SpO2 percentage',
    value_type: 'int',
    prompt_template: 'What is the SpO2?',
    clinical_label: 'SpO2',
  },
  gcs_total: {
    nemsis_element: 'eVitals.23',
    usage: 'required',
    section: 'eVitals',
    description: 'Glasgow Coma Scale total score',
    value_type: 'int',
    prompt_template: 'What is the GCS score?',
    clinical_label: 'GCS Total',
  },
  avpu: {
    nemsis_element: 'eVitals.26',
    usage: 'required',
    section: 'eVitals',
    description: 'AVPU responsiveness level',
    value_type: 'str',
    allowed_values: ['Alert', 'Verbal', 'Pain', 'Unresponsive'],
    prompt_template: "What is the patient's AVPU level?",
    clinical_label: 'AVPU',
  },
  pain_scale: {
    nemsis_element: 'eVitals.27',
    usage: 'recommended',
    section: 'eVitals',
    description: 'Pain scale rating (0–10)',
    value_type: 'int',
    prompt_template: "What is the patient's pain level on a scale of 0 to 10?",
    clinical_label: 'Pain Scale',
  },
  temperature: {
    nemsis_element: 'eVitals.24',
    usage: 'recommended',
    section: 'eVitals',
    description: 'Body temperature in °F',
    value_type: 'float',
    prompt_template: "What is the patient's temperature?",
    clinical_label: 'Temperature (°F)',
  },
  blood_glucose: {
    nemsis_element: 'eVitals.18',
    usage: 'recommended',
    section: 'eVitals',
    description: 'Blood glucose level in mg/dL',
    value_type: 'int',
    prompt_template: 'What is the blood glucose level?',
    clinical_label: 'Blood Glucose',
  },
  etco2: {
    nemsis_element: 'eVitals.16',
    usage: 'recommended',
    section: 'eVitals',
    description: 'End-tidal CO2 in mmHg',
    value_type: 'int',
    prompt_template: 'What is the EtCO2?',
    clinical_label: 'EtCO2',
  },
  cardiac_rhythm: {
    nemsis_element: 'eVitals.03',
    usage: 'recommended',
    section: 'eVitals',
    description: 'Cardiac rhythm interpretation',
    value_type: 'str',
    prompt_template: 'What is the cardiac rhythm?',
    clinical_label: 'Cardiac Rhythm',
  },

  // --- eMedications ---
  medications_given: {
    nemsis_element: 'eMedications.03',
    usage: 'required',
    section: 'eMedications',
    description: 'Medications administered during encounter',
    value_type: 'list[MedicationGiven]',
    prompt_template: 'Were any medications administered?',
    clinical_label: 'Medications Given',
  },

  // --- eProcedures ---
  procedures: {
    nemsis_element: 'eProcedures.03',
    usage: 'required',
    section: 'eProcedures',
    description: 'Procedures performed during encounter',
    value_type: 'list[str]',
    prompt_template: 'What procedures were performed?',
    clinical_label: 'Procedures',
  },

  // --- eNarrative ---
  narrative_text: {
    nemsis_element: 'eNarrative.01',
    usage: 'required',
    section: 'eNarrative',
    description: 'Free-text clinical narrative',
    value_type: 'str',
    prompt_template: 'Can you provide a brief narrative of the encounter?',
    clinical_label: 'Narrative',
  },
};

export const SECTION_ORDER: NEMSISSection[] = [
  'ePatient',
  'eScene',
  'eDispatch',
  'eProtocols',
  'eSituation',
  'eVitals',
  'eHistory',
  'eMedications',
  'eProcedures',
  'eNarrative',
];

export const SECTION_LABELS: Record<NEMSISSection, string> = {
  ePatient: 'Patient',
  eScene: 'Incident',
  eDispatch: 'Dispatch',
  eProtocols: 'Protocol',
  eSituation: 'Situation',
  eVitals: 'Vitals',
  eHistory: 'History',
  eMedications: 'Medications',
  eProcedures: 'Procedures',
  eNarrative: 'Narrative',
};
